services:
  db:
    image: postgis/postgis:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  api:
    build: .
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy
